update filesss

diff --git a/.github/workflows/readme-checker.yaml b/.github/workflows/readme-checker.yaml
--- a/.github/workflows/readme-checker.yaml
+++ b/.github/workflows/readme-checker.yaml
@@ -12,4 +12,5 @@ jobs:
         - uses: actions/checkout@v2
         - name: step readme checker
           run: |
-              ls -ali; if [ ! -f README.md ]; then echo "Failed: README.md not found." exit 1; fi
+              ls -ali; if [ ! -f README.md ]; then 
+                echo "Failed: README.md not found." exit 1; fi
