update filesss

diff --git a/.github/workflows/readme-checker.yaml b/.github/workflows/readme-checker.yaml
--- a/.github/workflows/readme-checker.yaml
+++ b/.github/workflows/readme-checker.yaml
@@ -13,4 +13,4 @@ jobs:
         - name: step readme checker
           run: |
               ls -ali; if [ ! -f README.md ]; then 
-                echo "Failed: README.md not found." exit 1; fi
+                echo "Failed: README.md not found."; exit 1; fi
